# -*- coding: utf-8 -*-
"""20200918typhon_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P9BV-qg4Lod6WhTfEgybEcwdOfHarrXl
"""

#!/usr/bin/python
# -*- coding: UTF-8 -*-
 
def swap(a,b):
    a,b = b,a
    return (a,b)
 
if __name__ == '__main__':
    x = 10
    y = 20
    print('x = %d,y = %d' % (x,y))
    x,y = swap(x,y)
    print('x = %d,y = %d' % (x,y))

#!/usr/bin/python 
# -*- coding: UTF-8 -*- 

def hello_3(greeting='Hello', name='world'): 
    print('{}, {}!'.format(greeting, name)) 

    
hello_3() 
hello_3('Greetings') 
hello_3('Greetings', 'universe')
hello_3(name='GGGGGGoood')

#!/usr/bin/python
# -*- coding: UTF-8 -*-

 
def age(n):
    if n == 1: c = 10
    else: c = age(n - 1) + 2
    return c
print (age(5))